endOfLine: lf
semi: false
printWidth: 120
singleQuote: false
tabWidth: 2
trailingComma: es5
plugins: [prettier-plugin-tailwindcss, prettier-plugin-classnames, prettier-plugin-merge]
customFunctions: [cva]
